apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-portal

spec:
  replicas: 1

  selector:
    matchLabels:
      app: employee-portal

  template:
    metadata:
      labels:
        app: employee-portal

    spec:
      containers:
      - name: employee-portal
        image: gsahasra333/employee-portal:IMAGE_TAG

        ports:
        - containerPort: 5000